'use client'

import { StandardSection as Ui_settings_StandardSection } from '@web-ui/components/settings/sections/StandardSection'
import { Button as UiButton } from '@web-ui/components/Button'
import { use_import } from './_hooks/use-import'
import { Checkbox as UiCheckbox } from '@web-ui/components/Checkbox'

const Page: React.FC = () => {
  const import_hook = use_import()

  const handle_file_change = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (!event.target.files) return
    const file = event.target.files[0]
    const reader = new FileReader()
    reader.onload = (e) => {
      import_hook.set_file_text(e.target?.result as string)
    }
    reader.readAsText(file)
  }

  return (
    <Ui_settings_StandardSection
      heading={{
        text: 'Import bookmarks',
        subtext:
          'Export file can be generated by your web browser, a third-party service or "Backups" settings pane.',
      }}
    >
      <div>
        <input type="file" onChange={handle_file_change} accept=".html,.json" />
      </div>
      <p>
        <small>
          The imported file will be validated and encrypted locally using your
          master password and will remain on your device until you choose to
          proceed. This guarantees the accuracy and security of the data.
        </small>
      </p>

      {import_hook.parsed_xml && (
        <>
          <br />
          <h3>File contents</h3>
          <p>Found {import_hook.parsed_xml.length} bookmarks.</p>
          <p>
            <small>
              <strong>Important:</strong> Individual bookmark visibility can be
              adjusted once import is complete.
            </small>
          </p>
          <br />
          <h3>Summary</h3>
          <p>
            You're about to import {import_hook.parsed_xml.length} bookmarks to
            your personal library.{' '}
          </p>
          <p>Would you like to proceed?</p>
          <br />
          <div>
            <UiButton
              is_disabled={import_hook.is_sending}
              on_click={import_hook.submit}
            >
              Proceeed
            </UiButton>
          </div>
        </>
      )}

      {import_hook.import_data && (
        <>
          <br />
          <h3>File contents</h3>
          <p>Found {import_hook.import_data.bookmarks.length} bookmarks</p>
          <br />
          <UiCheckbox
            label="Erase my library"
            on_click={() => {
              import_hook.set_erase_library(!import_hook.erase_library)
            }}
            is_checked={import_hook.erase_library}
          />
          <br />
          <p>Would you like to proceed?</p>
          <br />
          <div>
            <UiButton
              is_disabled={import_hook.is_sending}
              on_click={import_hook.submit}
            >
              Proceeed
            </UiButton>
          </div>
        </>
      )}
    </Ui_settings_StandardSection>
  )
}

export default Page
