declare const styles: {
  readonly container: string
  readonly 'container--has-highlights': string
  readonly bookmark: string
  readonly bookmark__top: string
  readonly bookmark__top__info: string
  readonly bookmark__top__menu: string
  readonly bookmark__top__menu__button: string
  readonly 'bookmark__top__menu--toggled': string
  readonly bookmark__top__menu__slot: string
  readonly 'bookmark__top__menu__slot--hidden': string
  readonly bookmark__title: string
  readonly bookmark__title__inner: string
  readonly bookmark__title__inner__unread: string
  readonly bookmark__title__inner__stars: string
  readonly bookmark__title__inner__text: string
  readonly 'bookmark__title__inner__text--unread': string
  readonly bookmark__tags: string
  readonly bookmark__tags__tag: string
  readonly bookmark__tags__tag__name: string
  readonly 'bookmark__tags__tag__name--selected': string
  readonly bookmark__tags__tag__yields: string
  readonly bookmark__links: string
  readonly bookmark__links__item: string
  readonly 'bookmark__links__item--has-highlights': string
  readonly bookmark__links__item__site: string
  readonly bookmark__links__item__site__favicon: string
  readonly 'bookmark__links__item__site__favicon--has-highlights': string
  readonly bookmark__links__item__site__url: string
  readonly bookmark__links__item__actions: string
  readonly bookmark__links__item__actions__open: string
  readonly bookmark__links__item__actions__menu: string
  readonly 'bookmark__links__item__actions__public-saves': string
  readonly highlight: string
}
export = styles
