export const chatbot_urls = {
  chatgpt: 'https://chatgpt.com/',
  gemini: 'https://gemini.google.com/app',
  mistral: 'https://chat.mistral.ai/chat',
  cohere: 'https://coral.cohere.com/',
  huggingchat: 'https://huggingface.co/chat/',
  aistudio: 'https://aistudio.google.com/app/prompts/new_chat',
  deepseek: 'https://chat.deepseek.com/',
  claude: 'https://claude.ai/new',
  phind: 'https://www.phind.com/agent',
  poe: 'https://poe.com/',
  grok: 'https://x.com/i/grok',
  meta: 'https://www.meta.ai/',
  you: 'https://you.com/',
  librechat: 'https://librechat-librechat.hf.space/c/new',
  perplexity: 'https://www.perplexity.ai/',
  copilot: 'https://www.bing.com/chat',
}
