'use client'

import { use_import } from '@/hooks/settings/import/use-import'
import { Box as UiAppAtom_Box } from '@web-ui/components/app/atoms/box'
import { BoxHeading as UiAppAtom_BoxHeading } from '@web-ui/components/app/atoms/box-heading'
import { RadioSetting as UiAppAtom_RadioSetting } from '@web-ui/components/app/atoms/radio-setting'
import { FormRadio as UiAppTemplate_FormRadio } from '@web-ui/components/app/templates/form-radio'
import { Button as UiCommonParticle_Button } from '@web-ui/components/common/particles/button'

const Page: React.FC = () => {
  const import_hook = use_import()

  const handle_file_change = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (!event.target.files) return
    const file = event.target.files[0]
    const reader = new FileReader()
    reader.onload = (e) => {
      import_hook.set_netscape_document(e.target?.result as string)
    }
    reader.readAsText(file)
  }

  return (
    <>
      <UiAppAtom_Box>
        <UiAppAtom_BoxHeading
          heading="Import bookmarks"
          subheading={
            'Export can be generated by your web browser, a third-party service or "Backups" settings pane.'
          }
        />

        {!import_hook.parsed_bookmarks ? (
          <>
            <div>
              <input type="file" onChange={handle_file_change} />
            </div>
            <p>
              <small>
                <strong>Privacy note:</strong> Chosen file will be validated
                locally. In the next step you will be asked to set visibility
                for all imported bookmarks and confirm file upload. Until then,
                no data will leave your device.
              </small>
            </p>
          </>
        ) : (
          <>
            <div>
              <UiCommonParticle_Button
                is_loading={import_hook.is_sending}
                on_click={import_hook.reset_state}
              >
                Select another file
              </UiCommonParticle_Button>
            </div>
            <h3>File details</h3>
            <p>Found {import_hook.parsed_bookmarks.length} bookmarks.</p>
            <h3>Visibility</h3>
            <UiAppTemplate_FormRadio>
              <UiAppAtom_RadioSetting
                top_line="Private"
                bottom_line="All bookmarks are encrypted end-to-end"
                on_click={() => {
                  import_hook.set_import_as_public(false)
                }}
                is_checked={!import_hook.import_as_public}
              />
              <UiAppAtom_RadioSetting
                top_line="Public"
                bottom_line="All bookmarks are published to your public profile"
                on_click={() => {
                  import_hook.set_import_as_public(true)
                }}
                is_checked={import_hook.import_as_public}
              />
            </UiAppTemplate_FormRadio>
            <p>
              <small>
                <strong>Note:</strong> Individual bookmark visibility can be
                adjusted once import is complete.
              </small>
            </p>
            <h3>Summary</h3>
            <p>
              You're about to import {import_hook.parsed_bookmarks.length}{' '}
              bookmarks to your personal library.{' '}
              {import_hook.import_as_public
                ? 'All of them will show up on your public profile. '
                : 'All of them will be kept secret to anyone, even us. '}
            </p>
            <div>
              <UiCommonParticle_Button
                is_loading={import_hook.is_sending}
                on_click={import_hook.submit}
                size="medium"
              >
                {import_hook.import_as_public
                  ? 'Upload file...'
                  : 'Upload encrypted file...'}
              </UiCommonParticle_Button>
            </div>
          </>
        )}
      </UiAppAtom_Box>
    </>
  )
}

export default Page
