'use client'

import { StandardSection as Ui_settings_StandardSection } from '@web-ui/components/settings/StandardSection'
import { Button as UiButton } from '@web-ui/components/Button'
import { use_import } from './_hooks/use-import'
import { Checkbox as UiCheckbox } from '@web-ui/components/Checkbox'

const Page: React.FC = () => {
  const import_hook = use_import()

  const handle_file_change = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (!event.target.files) return
    const file = event.target.files[0]
    const reader = new FileReader()
    reader.onload = (e) => {
      import_hook.set_file_text(e.target?.result as string)
    }
    reader.readAsText(file)
  }

  return (
    <Ui_settings_StandardSection
      heading={{
        text: 'Import bookmarks',
        subtext:
          'Export file can be generated by your web browser, a third-party service or "Backups" settings pane.',
      }}
    >
      <div>
        <input type="file" onChange={handle_file_change} accept=".html,.json" />
      </div>
      <p>
        <small>
          Imported file will be validated and encrypted with your master
          password locally and won't leave your device until you confirm upload.
          This ensures the data is accurate and secured.
        </small>
      </p>

      {import_hook.parsed_xml && (
        <>
          <h3>File contents</h3>
          <p>Found {import_hook.parsed_xml.length} bookmarks.</p>
          <p>
            <small>
              <strong>Important:</strong> Individual bookmark visibility can be
              adjusted once import is complete.
            </small>
          </p>
          <h3>Summary</h3>
          <p>
            You're about to import {import_hook.parsed_xml.length} bookmarks to
            your personal library.{' '}
          </p>
          <p>Would you like to proceed?</p>
          <br />
          <div>
            <UiButton
              is_disabled={import_hook.is_sending}
              on_click={import_hook.submit}
            >
              Proceeed
            </UiButton>
          </div>
        </>
      )}

      {import_hook.import_data && (
        <>
          <br />
          <h3>File contents</h3>
          <p>Found {import_hook.import_data.bookmarks.length} bookmarks</p>
          <br />
          <h3>Options</h3>
          <br />
          <UiCheckbox
            label="Erase library"
            on_click={() => {
              import_hook.set_erase_library(!import_hook.erase_library)
            }}
            is_checked={import_hook.erase_library}
          />
          <br />
          <p>Would you like to proceed?</p>
          <br />
          <div>
            <UiButton
              is_disabled={import_hook.is_sending}
              on_click={import_hook.submit}
            >
              Proceeed
            </UiButton>
          </div>
        </>
      )}
    </Ui_settings_StandardSection>
  )
}

export default Page
