'use client'

import { HeadingWithSubheading as UiAppAtom_HeadingWithSubheading } from '@web-ui/components/app/atoms/heading-with-subheading'
import { RadioSetting as UiAppAtom_RadioSetting } from '@web-ui/components/app/atoms/radio-setting'
import { Button as UiCommonParticle_Button } from '@web-ui/components/common/particles/button'
import { BoxDivider as UiAppAtom_BoxDivider } from '@web-ui/components/app/atoms/box-divider'
import { use_import } from './_hooks/use-import'

const Page: React.FC = () => {
  const import_hook = use_import()

  const handle_file_change = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (!event.target.files) return
    const file = event.target.files[0]
    const reader = new FileReader()
    reader.onload = (e) => {
      import_hook.set_file_text(e.target?.result as string)
    }
    reader.readAsText(file)
  }

  return (
    <div>
      <UiAppAtom_HeadingWithSubheading
        heading="Import bookmarks"
        subheading={
          'Export file can be generated by your web browser, a third-party service or "Backups" settings pane.'
        }
      />
      <div>
        <input type="file" onChange={handle_file_change} accept=".html,.json" />
      </div>
      <p>
        <small>
          Imported file will be validated and encrypted with your master
          password locally and won't leave your device until you confirm upload.
          This ensures the data is accurate and secured.
        </small>
      </p>

      {import_hook.parsed_xml && (
        <>
          <UiAppAtom_BoxDivider />
          <h3>File contents</h3>
          <p>Found {import_hook.parsed_xml.length} bookmarks.</p>
          <p>
            <small>
              <strong>Important:</strong> Individual bookmark visibility can be
              adjusted once import is complete.
            </small>
          </p>
          <h3>Summary</h3>
          <p>
            You're about to import {import_hook.parsed_xml.length} bookmarks to
            your personal library.{' '}
          </p>
          <p>Would you like to proceed?</p>
          <br />
          <div>
            <UiCommonParticle_Button
              is_disabled={import_hook.is_sending}
              on_click={import_hook.submit}
            >
              Proceeed
            </UiCommonParticle_Button>
          </div>
        </>
      )}

      {import_hook.import_data && (
        <>
          <UiAppAtom_BoxDivider />
          <h3>File contents</h3>
          <p>Found {import_hook.import_data.bookmarks.length} bookmarks.</p>
          <h3>Options</h3>
          <UiAppAtom_RadioSetting
            top_line="Erase library"
            bottom_line="Import will completely overwrite your library"
            on_click={() => {
              import_hook.set_erase_library(!import_hook.erase_library)
            }}
            is_checked={import_hook.erase_library}
          />
          <h3>Summary</h3>
          <p>
            This operation will restore deleted bookmarks. Changes to any
            existing bookmarks will not be overwritten.
          </p>
          <p>Would you like to proceed?</p>
          <br />
          <div>
            <UiCommonParticle_Button
              is_disabled={import_hook.is_sending}
              on_click={import_hook.submit}
            >
              Proceeed
            </UiCommonParticle_Button>
          </div>
        </>
      )}
    </div>
  )
}

export default Page
