declare const styles: {
  readonly container: string
  readonly input: string
  readonly 'input--yields-no-results': string
  readonly 'input--focus': string
  readonly 'input--focus-yields-no-results': string
  readonly 'input__left-side': string
  readonly input__loader: string
  readonly rotation: string
  readonly form: string
  readonly form__keycap: string
  readonly 'form__styled-value': string
  readonly 'form__styled-value--yields-no-results': string
  readonly 'form__styled-value__pre-highlight': string
  readonly 'form__styled-value__highlight': string
  readonly 'form__styled-value__highlight--no-results': string
  readonly 'form__styled-value__completion': string
  readonly 'input__right-side': string
  readonly 'input__right-side__press_key': string
  readonly 'input__right-side__results-count': string
  readonly 'input__right-side__results-count--yields-no-results': string
  readonly 'input__right-side__clear': string
  readonly 'input__right-side__clear--yields-no-results': string
  readonly hints: string
  readonly hints__inner: string
  readonly hints__inner__item: string
  readonly 'hints__inner__item--selected': string
  readonly hints__inner__item__icon: string
  readonly hints__inner__item__content: string
  readonly hints__inner__item__content__keycap: string
  readonly hints__inner__item__remove: string
  readonly text: string
  readonly skeleton: string
}
export = styles
