export const metadata = {
  title: '1Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      {children}
      <div>cipa</div>
    </div>
  )
}
