export const SITE_MAX_WIDTH = 1380
export const HEADER_DESKTOP_HEIGHT = 63
export const HEADER_MOBILE_HEIGHT = 45
export const BOTTOM_NAVIGATION_BAR_HEIGHT = 49
export const TRANSPARENT_BACKGROUND_COLOR = 'rgba(255, 255, 255, 0.8)'
export const BACKDROP_FILTER = 'saturate(180%) blur(5px)'
export const ICON_SIZE = 24
export const BUTTON_SIZE_46 = 46
export const APP_BAR_HEIGHT = 63
