name: Deploy web-client

on:
  push:
    branches:
      - master # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install
        working-directory: ./packages/web-client

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_API_URL=https://api.taaabs.com" >> .env
          echo "NEXT_PUBLIC_APP_URL=https://taaabs.com" >> .env
          echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=6LffM9UpAAAAAOD_kFg_BsrOWvFlOVHZO_heSwkz" >> .env
        working-directory: ./packages/web-client

      - name: Build Next.js app
        run: pnpm build
        working-directory: ./packages/web-client

      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          scp -r ./packages/web-client/.next $USERNAME@$HOST:/home/ubuntu/apps/taaabs/packages/web-client
          ssh $USERNAME@$HOST 'cd /home/ubuntu/apps/taaabs && git pull && pnpm i && pm2 reload taaabs-client'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Invalidate CloudFront distribution
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"